### ISSUE TITLE
App.config not found

### ISSUE THREAD

**Issue by baalan92** [aslamiqbal/BioMatrix#1]
The File App.config is is not found in the project folder

**Comment by aslamiqbal** [comment]
@baalan92 , here is the app.config file's code:


<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <configSections>
    </configSections>
    <connectionStrings>
        <add name="ZK_db" connectionString="Server=.;Database=ZK_db;User ID=sa;Password=yourpw;Trusted_Connection=False;" providerName="System.Data.SqlClient"/>
    </connectionStrings>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.0"/>
    </startup>
</configuration>

**Comment by baalan92** [comment]
I am unable to find it. And please update the bin/Debug folder too.

**Comment by aslamiqbal** [comment]
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <configSections>
    </configSections>
    <connectionStrings>
        <add name="ZK_db" connectionString="Server=.;Database=ZK_db;User ID=sa;Password=newtec.com;Trusted_Connection=False;" providerName="System.Data.SqlClient"/>
    </connectionStrings>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.0"/>
    </startup>
</configuration>

**Comment by aslamiqbal** [comment]
http://beta.salebee.net/app.7z

**Comment by aslamiqbal** [comment]
@baalan92 , Please try now above link.

**Comment by baalan92** [comment]
Thank you got it.
